# Generated by Django 4.2.30 on 2026-06-15 07:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=50)),
                ('address_text', models.CharField(max_length=300)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('is_default', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.client')),
            ],
            options={
                'ordering': ('-is_default', 'label'),
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('version', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Privacy policies',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MasterDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('file', models.FileField(upload_to='masters/documents/')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.master')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MasterCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('file', models.FileField(upload_to='masters/certificates/')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='accounts.master')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='clients/devices/')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('repair', "Ta'mirda"), ('broken', 'Ishlamayapti')], default='active', max_length=20)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='profiles.clientaddress')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.servicecategory')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_devices', to='accounts.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
