# Generated by Django 4.2.30 on 2026-06-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mastercertificate',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='masterdocument',
            options={'ordering': ('-created_at',)},
        ),
    ]
