# Generated by Django 4.2.30 on 2026-06-26 04:59

from django.db import migrations, models


def clear_description(apps, schema_editor):
    Tariff = apps.get_model('profiles', 'Tariff')
    Tariff.objects.update(description='[]')


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_mastercertificate_options_and_more'),
    ]

    operations = [
        migrations.RunPython(clear_description, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='tariff',
            name='description',
            field=models.JSONField(default=list),
        ),
    ]
