# Generated by Django 4.2.30 on 2026-06-26 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_tariff_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='description',
        ),
        migrations.AddField(
            model_name='tariff',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tariff',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TariffFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='profiles.tariff')),
            ],
        ),
    ]
