# Generated by Django 4.2.30 on 2026-06-26 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_tariff_description_tariff_is_popular_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariff',
            options={'ordering': ('sort_order', 'price', 'name')},
        ),
        migrations.AlterModelOptions(
            name='tarifffeature',
            options={'ordering': ('sort_order', 'id')},
        ),
    ]
