# Generated by Django 4.2.30 on 2026-07-05 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('profiles', '0005_alter_tariff_options_alter_tarifffeature_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientdevice',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='clientdevice',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='services.servicecategory'),
        ),
    ]
