# Generated by Django 4.2.30 on 2026-07-05 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_clientdevice_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdevice',
            name='category',
        ),
    ]
