# Generated by Django 4.2.30 on 2026-06-25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderTracking",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("master_lat", models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ("master_lng", models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ("distance_km", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("eta_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tracking", to="orders.order"
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
    ]
