# Generated by Codex on 2026-06-27

from django.db import migrations, models
import uuid


def seed_default_home_banner(apps, schema_editor):
    HomeBanner = apps.get_model("orders", "HomeBanner")
    HomeBanner.objects.get_or_create(
        key="home-services-discount",
        defaults={
            "badge_text": "Bugun 25% chegirma",
            "title": "Uy xizmatlariga maxsus chegirma",
            "discount_percent": 25,
            "cta_label": "Band qilish",
            "cta_action": "create_order",
            "target_type": "services",
            "target_value": "",
            "sort_order": 0,
            "is_active": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_ordertracking"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeBanner",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=80, unique=True)),
                ("badge_text", models.CharField(blank=True, max_length=120)),
                ("title", models.CharField(max_length=180)),
                ("discount_percent", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("cta_label", models.CharField(blank=True, max_length=80)),
                ("cta_action", models.CharField(blank=True, max_length=80)),
                ("target_type", models.CharField(default="services", max_length=50)),
                ("target_value", models.CharField(blank=True, max_length=160)),
                ("banner_image", models.ImageField(blank=True, null=True, upload_to="home/banners/")),
                ("external_banner_url", models.URLField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("sort_order", "-created_at"),
            },
        ),
        migrations.RunPython(seed_default_home_banner, migrations.RunPython.noop),
    ]
