# Generated by Codex on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_homebanner"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="before_photo",
            field=models.ImageField(blank=True, null=True, upload_to="orders/before/"),
        ),
    ]
