# Generated by Codex on 2026-06-30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("orders", "0004_order_before_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="receipt_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="receipt_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_order_receipts",
                to="accounts.master",
            ),
        ),
    ]
