# Generated by Django 4.2.30 on 2026-07-05 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_tariff_options_alter_tarifffeature_options'),
        ('orders', '0006_simplify_homebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='profiles.clientdevice'),
        ),
    ]
