# Generated by Django 4.2.30 on 2026-07-06 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_homebanner_banner_image'),
        ('orders', '0007_order_device'),
    ]

    operations = [
    ]
