# Generated by Django 4.2.30 on 2026-07-07 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_blockedmaster'),
        ('orders', '0008_merge_0007_homebanner_banner_image_0007_order_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('accepted', 'Qabul qilindi'), ('on_way', "Yo'lda"), ('arrived', 'Yetib keldi'), ('completed', 'Yakunlandi'), ('cancelled', 'Bekor qilindi'), ('rejected', 'Rad etildi')], default='new', max_length=30),
        ),
        migrations.CreateModel(
            name='OrderMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('has_accepted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_order_masters', to=settings.AUTH_USER_MODEL)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_orders', to='accounts.master')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_masters', to='orders.order')),
            ],
            options={
                'ordering': ('created_at',),
                'unique_together': {('order', 'master')},
            },
        ),
    ]
