# Generated by Django 4.2.30 on 2026-07-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_is_paid_order_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completion_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('cash', 'Naqd'), ('online', 'Online'), ('card', 'Karta'), ('plastic', 'Plastik')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('accepted', 'Qabul qilindi'), ('on_way', "Yo'lda"), ('arrived', 'Yetib keldi'), ('awaiting_payment', "To'lov kutilmoqda"), ('completed', 'Yakunlandi'), ('cancelled', 'Bekor qilindi'), ('rejected', 'Rad etildi')], default='new', max_length=30),
        ),
    ]
