# Generated by Django 4.2.30 on 2026-07-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_fcm_token_lengths'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterApplication',
            fields=[
            ],
            options={
                'verbose_name': 'Ariza qoldirgan usta',
                'verbose_name_plural': 'Ariza qoldirgan ustalar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.master',),
        ),
    ]
