# Generated by Django 4.2.30 on 2026-07-05 19:06

from django.db import migrations, models


def backfill_is_blocked(apps, schema_editor):
    # Masters previously deactivated (is_active=False) that were NOT rejected
    # applications were effectively "blocked" — mark them explicitly.
    Master = apps.get_model("accounts", "Master")
    Master.objects.filter(is_active=False).exclude(approval_status="rejected").update(is_blocked=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_masterapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='block_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='master',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='master',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_is_blocked, migrations.RunPython.noop),
    ]
