# Generated by Django 4.2.30 on 2026-07-05 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_master_block_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedMaster',
            fields=[
            ],
            options={
                'verbose_name': 'Bloklangan usta',
                'verbose_name_plural': 'Bloklangan ustalar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.master',),
        ),
    ]
