# Generated by Django 4.2.30 on 2026-07-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_blockedmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='master',
            name='daraja',
            field=models.CharField(blank=True, choices=[('usta', 'Usta'), ('katta_usta', 'Katta usta')], max_length=20),
        ),
    ]
