# Generated by Django 4.2.30 on 2026-07-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='mxik',
            field=models.CharField(blank=True, max_length=32, verbose_name='IKPU/MXIK'),
        ),
        migrations.AddField(
            model_name='service',
            name='package_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='service',
            name='vat_percent',
            field=models.PositiveSmallIntegerField(default=12, verbose_name='QQS %'),
        ),
    ]
