from django.urls import path

from . import views


urlpatterns = [
    path("dashboard/overview/", views.DashboardOverviewAPIView.as_view(), name="internal-dashboard-overview"),
    path("dashboard/meta/", views.DashboardMetaAPIView.as_view(), name="internal-dashboard-meta"),
    path("dashboard/stats/", views.DashboardStatsAPIView.as_view(), name="internal-dashboard-stats"),
    path("dashboard/orders-by-service/", views.DashboardOrdersByServiceAPIView.as_view(), name="internal-dashboard-orders-by-service"),
    path("dashboard/orders-weekly/", views.DashboardWeeklyOrdersAPIView.as_view(), name="internal-dashboard-orders-weekly"),
    path("dashboard/income-dynamics/", views.DashboardIncomeDynamicsAPIView.as_view(), name="internal-dashboard-income-dynamics"),
    path("dashboard/income-expense/", views.DashboardIncomeExpenseAPIView.as_view(), name="internal-dashboard-income-expense"),
    path("dashboard/today-orders/", views.DashboardTodayOrdersAPIView.as_view(), name="internal-dashboard-today-orders"),
    path("dashboard/search/", views.DashboardSearchAPIView.as_view(), name="internal-dashboard-search"),
    path("clients/", views.ClientCollectionAPIView.as_view(), name="internal-clients-list-create"),
    path("clients/summary/", views.ClientSummaryAPIView.as_view(), name="internal-clients-summary"),
    path("clients/<uuid:pk>/", views.ClientDetailAPIView.as_view(), name="internal-clients-detail"),
    path("clients/<uuid:pk>/orders/", views.ClientOrdersAPIView.as_view(), name="internal-clients-orders"),
    path("clients/<uuid:pk>/stats/", views.ClientStatsAPIView.as_view(), name="internal-clients-stats"),
    path("masters/", views.MasterCollectionAPIView.as_view(), name="internal-masters-list-create"),
    path("masters/meta/", views.MasterMetaAPIView.as_view(), name="internal-masters-meta"),
    path("masters/stats/", views.MasterStatsAPIView.as_view(), name="internal-masters-stats"),
    path("masters/available/", views.AvailableMastersAPIView.as_view(), name="internal-masters-available"),
    path("masters/assistants/", views.AssistantCollectionAPIView.as_view(), name="internal-assistants-list-create"),
    path("masters/assistants/<uuid:pk>/", views.AssistantDetailAPIView.as_view(), name="internal-assistants-detail"),
    path("masters/<uuid:pk>/", views.MasterDetailAPIView.as_view(), name="internal-masters-detail"),
    path("masters/<uuid:pk>/assistants/", views.MasterAssistantCollectionAPIView.as_view(), name="internal-masters-assistants"),
    path("masters/<uuid:pk>/assistants/<uuid:assistant_id>/", views.MasterAssistantDetachAPIView.as_view(), name="internal-masters-assistants-detach"),
    path("masters/<uuid:pk>/block/", views.MasterBlockAPIView.as_view(), name="internal-masters-block"),
    path("masters/<uuid:pk>/location/", views.MasterLocationAPIView.as_view(), name="internal-masters-location"),
    path("masters/<uuid:pk>/status/", views.MasterStatusAPIView.as_view(), name="internal-masters-status"),
    path("masters/<uuid:pk>/orders/", views.MasterOrdersAPIView.as_view(), name="internal-masters-orders"),
    path("masters/<uuid:pk>/schedule/", views.MasterScheduleAPIView.as_view(), name="internal-masters-schedule"),
    path("masters/<uuid:pk>/income/", views.MasterIncomeAPIView.as_view(), name="internal-masters-income"),
    path("masters/<uuid:pk>/verify/", views.MasterVerifyAPIView.as_view(), name="internal-masters-verify"),
    path("services/categories/", views.ServiceCategoryCollectionAPIView.as_view(), name="internal-service-categories-list-create"),
    path("services/categories/<uuid:pk>/", views.ServiceCategoryDetailAPIView.as_view(), name="internal-service-categories-detail"),
    path("services/categories/<uuid:pk>/toggle/", views.ServiceCategoryToggleAPIView.as_view(), name="internal-service-categories-toggle"),
    path("services/categories/<uuid:pk>/services/", views.CategoryServicesAPIView.as_view(), name="internal-service-categories-services"),
    path("services/meta/", views.ServiceMetaAPIView.as_view(), name="internal-services-meta"),
    path("services/", views.ServiceCollectionAPIView.as_view(), name="internal-services-list-create"),
    path("services/<uuid:pk>/", views.ServiceDetailAPIView.as_view(), name="internal-services-detail"),
    path("tariffs/", views.TariffCollectionAPIView.as_view(), name="internal-tariffs-list-create"),
    path("tariffs/meta/", views.TariffMetaAPIView.as_view(), name="internal-tariffs-meta"),
    path("tariffs/current/", views.CurrentTariffAPIView.as_view(), name="internal-tariffs-current"),
    path("tariffs/subscribe/", views.SubscribeTariffAPIView.as_view(), name="internal-tariffs-subscribe"),
    path("tariffs/<uuid:pk>/", views.TariffDetailAPIView.as_view(), name="internal-tariffs-detail"),
    path("orders/dashboard/stats/", views.DashboardStatsAPIView.as_view(), name="internal-orders-dashboard-stats"),
    path("orders/dashboard/by-service/", views.DashboardOrdersByServiceAPIView.as_view(), name="internal-orders-dashboard-by-service"),
    path("orders/dashboard/weekly/", views.DashboardWeeklyOrdersAPIView.as_view(), name="internal-orders-dashboard-weekly"),
    path("orders/dashboard/today/", views.DashboardTodayOrdersAPIView.as_view(), name="internal-orders-dashboard-today"),
    path("orders/", views.OrderCollectionAPIView.as_view(), name="internal-orders-list-create"),
    path("orders/meta/", views.OrderMetaAPIView.as_view(), name="internal-orders-meta"),
    path("orders/board/", views.OrderBoardAPIView.as_view(), name="internal-orders-board"),
    path("orders/express/", views.OrderExpressCreateAPIView.as_view(), name="internal-orders-express-create"),
    path("orders/export/", views.OrderExportAPIView.as_view(), name="internal-orders-export"),
    path("orders/<uuid:pk>/", views.OrderDetailAPIView.as_view(), name="internal-orders-detail"),
    path("orders/<uuid:pk>/assignment-options/", views.OrderAssignmentOptionsAPIView.as_view(), name="internal-orders-assignment-options"),
    path("orders/<uuid:pk>/assistants/", views.OrderAssistantCollectionAPIView.as_view(), name="internal-orders-assistants"),
    path("orders/<uuid:pk>/assistants/<uuid:assistant_id>/", views.OrderAssistantDetachAPIView.as_view(), name="internal-orders-assistants-detach"),
    path("orders/<uuid:pk>/receipt/download/", views.OrderReceiptDownloadAPIView.as_view(), name="internal-orders-receipt-download"),
    path("orders/<uuid:pk>/status/", views.OrderStatusAPIView.as_view(), name="internal-orders-status"),
    path("orders/<uuid:pk>/assign/", views.OrderAssignAPIView.as_view(), name="internal-orders-assign"),
]
