# Generated by Django 4.2.30 on 2026-06-15 07:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('unit', models.CharField(default='dona', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('low_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='warehouse/products/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('kirim', 'Kirim'), ('chiqim', 'Chiqim')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.master')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='warehouse.warehouseproduct')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MasterInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(default='dona', max_length=20)),
                ('low_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='masters/inventory/')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='accounts.master')),
                ('warehouse_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master_items', to='warehouse.warehouseproduct')),
            ],
            options={
                'ordering': ('warehouse_product__name',),
                'unique_together': {('master', 'warehouse_product')},
            },
        ),
    ]
