# Generated by Django 4.2.30 on 2026-07-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_warehousecategory_warehouseproduct_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproduct',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='warehouseproduct',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
