# Generated by Django 4.2.30 on 2026-07-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_warehouseproduct_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproduct',
            name='mxik',
            field=models.CharField(blank=True, max_length=32, verbose_name='IKPU/MXIK'),
        ),
        migrations.AddField(
            model_name='warehouseproduct',
            name='package_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='warehouseproduct',
            name='vat_percent',
            field=models.PositiveSmallIntegerField(default=12, verbose_name='QQS %'),
        ),
    ]
