# Generated by Django 4.2.30 on 2026-07-11 17:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0011_order_is_paid_order_paid_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymeTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('state', models.IntegerField(choices=[(0, 'Created'), (1, 'Initiating'), (2, 'Performed'), (-2, 'Cancelled after perform'), (-1, 'Cancelled during initiation')], default=0)),
                ('fiscal_data', models.JSONField(blank=True, default=dict)),
                ('cancel_reason', models.IntegerField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payme_transactions', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payme Transaction',
                'verbose_name_plural': 'Payme Transactions',
                'db_table': 'payme_transactions',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['created_at'], name='payme_trans_created_85b635_idx'), models.Index(fields=['order', 'state'], name='payme_trans_order_i_c66595_idx')],
            },
        ),
    ]
