# Generated by Django 4.2.30 on 2026-06-29 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def backfill_support_chats(apps, schema_editor):
    SupportChat = apps.get_model("support", "SupportChat")
    SupportMessage = apps.get_model("support", "SupportMessage")

    for message in SupportMessage.objects.filter(chat__isnull=True).order_by("created_at"):
        if message.master_id:
            chat, _ = SupportChat.objects.get_or_create(
                master_id=message.master_id,
                defaults={"participant_role": "master"},
            )
        elif message.client_id:
            chat, _ = SupportChat.objects.get_or_create(
                client_id=message.client_id,
                defaults={"participant_role": "client"},
            )
        else:
            continue

        message.chat_id = chat.id
        message.save(update_fields=["chat"])
        if not chat.created_at or chat.created_at > message.created_at:
            chat.created_at = message.created_at
        if not chat.updated_at or chat.updated_at < message.updated_at:
            chat.updated_at = message.updated_at
        chat.save(update_fields=["created_at", "updated_at"])

    for chat in SupportChat.objects.all():
        chat.unread_by_admin = SupportMessage.objects.filter(
            chat=chat,
            sender_role__in=("client", "master"),
            is_read=False,
        ).count()
        chat.save(update_fields=["unread_by_admin"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_master_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SupportChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant_role', models.CharField(choices=[('client', 'Client'), ('master', 'Master')], max_length=20)),
                ('unread_by_admin', models.PositiveIntegerField(default=0)),
                ('client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_chat', to='accounts.client')),
                ('master', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_chat', to='accounts.master')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportchat'),
        ),
        migrations.RunPython(backfill_support_chats, noop_reverse),
        migrations.AddIndex(
            model_name='supportchat',
            index=models.Index(fields=['participant_role', 'updated_at'], name='support_sup_partici_ad2c2e_idx'),
        ),
    ]
