# Generated by Django 4.2.30 on 2026-07-05 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashHandover',
            fields=[
            ],
            options={
                'verbose_name': 'Masterdan naqd pul',
                'verbose_name_plural': 'Masterdan naqd pul qabul qilish',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wallet.withdrawrequest',),
        ),
    ]
