from django.urls import path

from apps.dashboard import views


urlpatterns = [
    path("auth/login/", views.DashboardLoginAPIView.as_view(), name="dashboard-auth-login"),
    path("auth/refresh/", views.DashboardRefreshAPIView.as_view(), name="dashboard-auth-refresh"),
    path("auth/logout/", views.DashboardLogoutAPIView.as_view(), name="dashboard-auth-logout"),
    path("auth/me/", views.DashboardMeAPIView.as_view(), name="dashboard-auth-me"),
    path("overview/", views.DashboardOverviewAPIView.as_view(), name="dashboard-overview"),
    path("meta/", views.DashboardMetaAPIView.as_view(), name="dashboard-meta"),
    path("stats/", views.DashboardStatsAPIView.as_view(), name="dashboard-stats"),
    path("orders-by-service/", views.DashboardOrdersByServiceAPIView.as_view(), name="dashboard-orders-by-service"),
    path("orders-weekly/", views.DashboardWeeklyOrdersAPIView.as_view(), name="dashboard-orders-weekly"),
    path("income-dynamics/", views.DashboardIncomeDynamicsAPIView.as_view(), name="dashboard-income-dynamics"),
    path("income-expense/", views.DashboardIncomeExpenseAPIView.as_view(), name="dashboard-income-expense"),
    path("today-orders/", views.DashboardTodayOrdersAPIView.as_view(), name="dashboard-today-orders"),
    path("search/", views.DashboardSearchAPIView.as_view(), name="dashboard-search"),
    path("clients/", views.DashboardClientListCreateAPIView.as_view(), name="dashboard-clients"),
    path("clients/<uuid:pk>/", views.DashboardClientDetailAPIView.as_view(), name="dashboard-client-detail"),
    path("clients/<uuid:pk>/orders/", views.DashboardClientOrdersAPIView.as_view(), name="dashboard-client-orders"),
    path("clients/<uuid:pk>/stats/", views.DashboardClientStatsAPIView.as_view(), name="dashboard-client-stats"),
    path("staff/", views.DashboardStaffListCreateAPIView.as_view(), name="dashboard-staff"),
    path("staff/<int:pk>/", views.DashboardStaffDetailAPIView.as_view(), name="dashboard-staff-detail"),
    path("maps/masters/", views.DashboardMapMastersAPIView.as_view(), name="dashboard-map-masters"),
    path("masters/", views.DashboardMasterListCreateAPIView.as_view(), name="dashboard-masters"),
    path("masters/available/", views.DashboardAvailableMastersAPIView.as_view(), name="dashboard-masters-available"),
    path("masters/specializations/", views.DashboardMasterSpecializationsAPIView.as_view(), name="dashboard-masters-specializations"),
    path("masters/applications/", views.DashboardMasterApplicationListAPIView.as_view(), name="dashboard-masters-applications"),
    path("masters/blocked/", views.DashboardBlockedMasterListAPIView.as_view(), name="dashboard-masters-blocked"),
    path("masters/<uuid:pk>/block/", views.DashboardMasterBlockAPIView.as_view(), name="dashboard-master-block"),
    path("masters/<uuid:pk>/", views.DashboardMasterDetailAPIView.as_view(), name="dashboard-master-detail"),
    path("masters/<uuid:pk>/location/", views.DashboardMasterLocationAPIView.as_view(), name="dashboard-master-location"),
    path("masters/<uuid:pk>/status/", views.DashboardMasterStatusAPIView.as_view(), name="dashboard-master-status"),
    path("masters/<uuid:pk>/orders/", views.DashboardMasterOrdersAPIView.as_view(), name="dashboard-master-orders"),
    path("masters/<uuid:pk>/wallet/", views.DashboardMasterWalletAPIView.as_view(), name="dashboard-master-wallet"),
    path("cash-handovers/", views.DashboardCashHandoverListAPIView.as_view(), name="dashboard-cash-handovers"),
    path("cash-handovers/<uuid:pk>/accept/", views.DashboardCashHandoverAcceptAPIView.as_view(), name="dashboard-cash-handover-accept"),
    path("cash-handovers/<uuid:pk>/reject/", views.DashboardCashHandoverRejectAPIView.as_view(), name="dashboard-cash-handover-reject"),
    path("orders/", views.DashboardOrderListCreateAPIView.as_view(), name="dashboard-orders"),
    path("orders/board/", views.DashboardOrderBoardAPIView.as_view(), name="dashboard-orders-board"),
    path("orders/<uuid:pk>/", views.DashboardOrderDetailAPIView.as_view(), name="dashboard-order-detail"),
    path("orders/<uuid:pk>/status/", views.DashboardOrderStatusAPIView.as_view(), name="dashboard-order-status"),
    path("orders/<uuid:pk>/assign/", views.DashboardOrderAssignAPIView.as_view(), name="dashboard-order-assign"),
    path("orders/<uuid:pk>/tracking/", views.DashboardOrderTrackingAPIView.as_view(), name="dashboard-order-tracking"),
    path("orders/<uuid:pk>/assistants/", views.DashboardOrderAssistantListCreateAPIView.as_view(), name="dashboard-order-assistants"),
    path(
        "orders/<uuid:pk>/assistants/<uuid:assistant_pk>/",
        views.DashboardOrderAssistantDetailAPIView.as_view(),
        name="dashboard-order-assistant-detail",
    ),
    path("services/categories/", views.DashboardServiceCategoryListCreateAPIView.as_view(), name="dashboard-service-categories"),
    path(
        "services/categories/<uuid:pk>/",
        views.DashboardServiceCategoryDetailAPIView.as_view(),
        name="dashboard-service-category-detail",
    ),
    path("services/", views.DashboardServiceListCreateAPIView.as_view(), name="dashboard-services"),
    path("services/<uuid:pk>/", views.DashboardServiceDetailAPIView.as_view(), name="dashboard-service-detail"),
    path("services/<uuid:service_id>/prices/", views.DashboardServicePriceListCreateAPIView.as_view(), name="dashboard-service-prices"),
    path("services/prices/<uuid:pk>/", views.DashboardServicePriceDetailAPIView.as_view(), name="dashboard-service-price-detail"),
    path("tariffs/", views.DashboardTariffListCreateAPIView.as_view(), name="dashboard-tariffs"),
    path("tariffs/<uuid:pk>/", views.DashboardTariffDetailAPIView.as_view(), name="dashboard-tariff-detail"),
    path("tariffs/<uuid:tariff_id>/features/", views.DashboardTariffFeatureListCreateAPIView.as_view(), name="dashboard-tariff-features"),
    path("tariffs/features/<int:pk>/", views.DashboardTariffFeatureDetailAPIView.as_view(), name="dashboard-tariff-feature-detail"),
    path("market/categories/", views.DashboardMarketCategoryListCreateAPIView.as_view(), name="dashboard-market-categories"),
    path("market/categories/<uuid:pk>/", views.DashboardMarketCategoryDetailAPIView.as_view(), name="dashboard-market-category-detail"),
    path("market/products/", views.DashboardMarketProductListCreateAPIView.as_view(), name="dashboard-market-products"),
    path("market/products/<uuid:pk>/", views.DashboardMarketProductDetailAPIView.as_view(), name="dashboard-market-product-detail"),
    path("market/products/<uuid:product_id>/images/", views.DashboardMarketProductImageListCreateAPIView.as_view(), name="dashboard-market-product-images"),
    path("market/images/<uuid:pk>/", views.DashboardMarketProductImageDetailAPIView.as_view(), name="dashboard-market-product-image-detail"),
    path("market/orders/", views.DashboardMarketOrderListCreateAPIView.as_view(), name="dashboard-market-orders"),
    path("market/orders/<uuid:pk>/", views.DashboardMarketOrderDetailAPIView.as_view(), name="dashboard-market-order-detail"),
    path("warehouse/stats/", views.DashboardWarehouseStatsAPIView.as_view(), name="dashboard-warehouse-stats"),
    path("warehouse/categories/", views.DashboardWarehouseCategoryListCreateAPIView.as_view(), name="dashboard-warehouse-categories"),
    path("warehouse/categories/<uuid:pk>/", views.DashboardWarehouseCategoryDetailAPIView.as_view(), name="dashboard-warehouse-category-detail"),
    path("warehouse/products/", views.DashboardWarehouseProductListCreateAPIView.as_view(), name="dashboard-warehouse-products"),
    path("warehouse/products/<uuid:pk>/", views.DashboardWarehouseProductDetailAPIView.as_view(), name="dashboard-warehouse-product-detail"),
    path("warehouse/movements/", views.DashboardStockMovementListCreateAPIView.as_view(), name="dashboard-stock-movements"),
    path("warehouse/movements/<uuid:pk>/", views.DashboardStockMovementDetailAPIView.as_view(), name="dashboard-stock-movement-detail"),
    path("warehouse/master-inventory/", views.DashboardMasterInventoryListCreateAPIView.as_view(), name="dashboard-master-inventory"),
    path("warehouse/master-inventory/<uuid:pk>/", views.DashboardMasterInventoryDetailAPIView.as_view(), name="dashboard-master-inventory-detail"),
    path("live-streams/", views.DashboardLiveStreamListCreateAPIView.as_view(), name="dashboard-live-streams"),
    path("live-streams/<uuid:pk>/", views.DashboardLiveStreamDetailAPIView.as_view(), name="dashboard-live-stream-detail"),
    path("archived-videos/", views.DashboardArchivedVideoListAPIView.as_view(), name="dashboard-archived-videos"),
    path("support/threads/", views.DashboardSupportThreadListAPIView.as_view(), name="dashboard-support-threads"),
    path("support/messages/", views.DashboardSupportMessageListCreateAPIView.as_view(), name="dashboard-support-messages"),
    path("support/messages/<uuid:pk>/", views.DashboardSupportMessageDetailAPIView.as_view(), name="dashboard-support-message-detail"),
    path("support/messages/<uuid:pk>/read/", views.DashboardSupportMessageReadAPIView.as_view(), name="dashboard-support-message-read"),
    path("wallet/transactions/", views.DashboardWalletTransactionListCreateAPIView.as_view(), name="dashboard-wallet-transactions"),
    path("wallet/transactions/<uuid:pk>/", views.DashboardWalletTransactionDetailAPIView.as_view(), name="dashboard-wallet-transaction-detail"),
    path("withdraw-requests/", views.DashboardWithdrawRequestListCreateAPIView.as_view(), name="dashboard-withdraw-requests"),
    path("withdraw-requests/<uuid:pk>/", views.DashboardWithdrawRequestDetailAPIView.as_view(), name="dashboard-withdraw-request-detail"),
    path("notifications/", views.DashboardNotificationListCreateAPIView.as_view(), name="dashboard-notifications"),
    path(
        "notifications/unread-count/",
        views.DashboardNotificationUnreadCountAPIView.as_view(),
        name="dashboard-notifications-unread-count",
    ),
    path(
        "notifications/read-all/",
        views.DashboardNotificationReadAllAPIView.as_view(),
        name="dashboard-notifications-read-all",
    ),
    path(
        "notifications/<uuid:pk>/",
        views.DashboardNotificationDetailAPIView.as_view(),
        name="dashboard-notification-detail",
    ),
    path(
        "notifications/<uuid:pk>/read/",
        views.DashboardNotificationReadAPIView.as_view(),
        name="dashboard-notification-read",
    ),
    path("expenses/", views.DashboardExpenseListCreateAPIView.as_view(), name="dashboard-expenses"),
    path("expenses/<uuid:pk>/", views.DashboardExpenseDetailAPIView.as_view(), name="dashboard-expense-detail"),
    path("company-expenses/", views.DashboardCompanyExpenseListCreateAPIView.as_view(), name="dashboard-company-expenses"),
    path("company-expenses/<uuid:pk>/", views.DashboardCompanyExpenseDetailAPIView.as_view(), name="dashboard-company-expense-detail"),
    path("warehouse-expenses/", views.DashboardWarehouseExpenseListCreateAPIView.as_view(), name="dashboard-warehouse-expenses"),
    path("warehouse-expenses/<uuid:pk>/", views.DashboardWarehouseExpenseDetailAPIView.as_view(), name="dashboard-warehouse-expense-detail"),
    path("finance/summary/", views.DashboardFinanceSummaryAPIView.as_view(), name="dashboard-finance-summary"),
    path("finance/income-by-service/", views.DashboardIncomeByServiceAPIView.as_view(), name="dashboard-finance-income-by-service"),
    path("finance/top-clients/", views.DashboardTopClientsAPIView.as_view(), name="dashboard-finance-top-clients"),
    path("finance/report/", views.DashboardFinanceReportAPIView.as_view(), name="dashboard-finance-report"),
    path("finance/export/", views.DashboardFinanceExportAPIView.as_view(), name="dashboard-finance-export"),
    path("settings/integrations/", views.DashboardIntegrationSettingListCreateAPIView.as_view(), name="dashboard-integration-settings"),
    path("settings/integrations/<uuid:pk>/", views.DashboardIntegrationSettingDetailAPIView.as_view(), name="dashboard-integration-setting-detail"),
    path("backups/", views.DashboardBackupListCreateAPIView.as_view(), name="dashboard-backups"),
    path("backups/settings/", views.DashboardBackupSettingsAPIView.as_view(), name="dashboard-backup-settings"),
    path("backups/<uuid:pk>/", views.DashboardBackupDetailAPIView.as_view(), name="dashboard-backup-detail"),
    path("backups/<uuid:pk>/download/", views.DashboardBackupDownloadAPIView.as_view(), name="dashboard-backup-download"),
]
